name: Publish to TestPyPi

on: workflow_dispatch

jobs:
  pypi:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-python@v2
      with:
        python-version: "3.9"
    
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install build twine
        python3 -m pip install -r requirements.txt

    - name: Pull EdgeFunction
      run: python3 edgefxn.py

    - name: Build Function
      run: python3 -m build

    - name: Publish to TestPyPi
      run: python3 -m twine upload dist/*
      env:
        TWINE_REPOSITORY: testpypi
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.TEST_PYPI_TOKEN }}

    - uses: actions/upload-artifact@v4
      with:
          name: Wheels
          path: dist/